services:
  app:
    build:
      dockerfile: dockerfile
      context: ./
    ports:
      - "8000:8000"

  pg: 
    image: postgres:17.5
    environment:
      POSTGRES_DB: mikoblog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"